# Generated by Django 4.2.28 on 2026-03-02 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newsroom.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsroomHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('article_id', models.CharField(default=newsroom.models.generate_article_id, editable=False, max_length=30, unique=True)),
                ('section', models.CharField(choices=[('economy', 'Economy'), ('society', 'Society'), ('policy', 'Policy')], default='policy', max_length=24)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('writing', 'Writing'), ('desk_review', 'Desk Review'), ('desk_rework', 'Desk Rework'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('published_updated', 'Published Updated'), ('retracted', 'Retracted'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('last_edit_level', models.CharField(blank=True, choices=[('L1', 'L1 (Minor)'), ('L2', 'L2 (Important)'), ('L3', 'L3 (Critical)')], max_length=2)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, help_text='예약 시간은 Asia/Seoul 기준으로 입력하고 UTC로 저장한다.', null=True)),
                ('correction_note', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('published_revision_no', models.PositiveIntegerField(default=0, editable=False)),
                ('correction_of', models.ForeignKey(blank=True, help_text='L3 정정/추후/반론 기사일 때 원기사를 연결한다.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l3_followups', to='newsroom.articlepage')),
                ('desk_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desk_reviewed_articles', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('submit_desk_review', 'Can move article to desk_review'), ('approve_article', 'Can approve and publish article'), ('schedule_article', 'Can schedule article'), ('retract_article', 'Can retract article'), ('archive_article', 'Can archive article'), ('apply_l2_update', 'Can perform L2 published update'), ('create_l3_followup', 'Can create L3 follow-up article')),
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_audit_events', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='newsroom.articlepage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
