# Generated by Django 4.2.28 on 2026-03-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='ai_external_id',
            field=models.CharField(blank=True, editable=False, help_text='Idempotency key from AI ingestion pipeline.', max_length=120, null=True, unique=True),
        ),
    ]
